PORTNAME=	ente-museum
PORTVERSION=	1.7.2
DISTVERSIONPREFIX=	photosd-v
CATEGORIES=	graphics

MAINTAINER=	kytomaki@iki.fi
COMMENT=	End to End Encrypted alternative to Google Photos and Apple Photos
WWW=		https://ente.io/

LICENSE=	AGPLv3

USES=			go:modules
USE_GITHUB=		yes
GH_ACCOUNT=		ente-io
GH_PROJECT=		ente

GO_TARGETS=		server/cmd/museum 

.include <bsd.port.mk>
