PORTNAME=		freebsd-rustdate
DISTVERSION=		1.2.1
CATEGORIES=		sysutils
MASTER_SITES=		https://rustdate.over-yonder.net/dl/
DISTFILES=		${PORTNAME}-${DISTVERSION}.tar.xz

MAINTAINER=		kytomaki@iki.fi
COMMENT=		Reimplementation of freebsd-update in rust
WWW=			https://rustdate.over-yonder.net/

LICENSE=		BSD2CLAUSE

USES=			cargo ssl

.include <bsd.port.mk>
