PORTNAME=		chirpstack
DISTVERSIONPREFIX= 	v
DISTVERSION=		4.14.1
CATEGORIES=		net

MAINTAINER=		kytomaki@iki.fi
COMMENT=		LoRaWAN(TM) Network Server
WWW=			https://www.chirpstack.io

LICENSE=		MIT

USES=			cargo
USE_GITHUB=		yes
GH_ACCOUNT=		${PORTNAME}
GH_PROJECT=		${PORTNAME}

CARGO_CARGOTOML=	${WORKSRC}/chirpstack/Cargo.toml

.include <bsd.port.mk>
