name: Test

on: [push]

jobs:
  matrix-output:
    runs-on: ubuntu-latest
    name: Create matrix based on directories
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create matrix
      id: matrix
      run: |
        echo "matrix=$(jq -njc --arg dirs "$(git diff --dirstat=files,0 origin/main -- | sed -E 's/[ 0-9.]+% //g' | cut -d'/' -f1,2 | sort -u | grep -v '.github/')" '$dirs | split("\n")')" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    name: Test port
    needs: matrix-output
    if: needs.matrix-output.outputs.matrix != '[]'
    strategy:
      fail-fast: false
      matrix:
        port: ${{ fromJson(needs.matrix-output.outputs.matrix) }}
        freebsd:
          - "13.4"
          - "13.5"
          - "14.2"
          - "14.3"
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: "${{ matrix.freebsd }}"
        prepare: |
          pkg install -y \
            ports-mgmt/porttools \
            ports-mgmt/portconfig \
            ports-mgmt/portconf

        run: |
          set -e
          echo "::group::Clone ports and configure git"
          git clone --depth 1 https://git.FreeBSD.org/ports.git /usr/ports
          git config --global --add safe.directory "${{ github.GITHUB_WORKSPACE }}"
          echo "::endgroup::"
          echo "::group::portlint"
          (cd ${{ matrix.port }} && /usr/local/bin/portlint -A)
          echo "::endgroup::"
          echo "::group::Install depends"
          make -C ${{ matrix.port }} build-depends-list | cut -c 12- | xargs pkg install -y
          echo "::endgroup::"
          echo "::group::Make test"
          make -C ${{ matrix.port }} test
          echo "::endgroup::"
          echo "::group::Make stage"
          make -C ${{ matrix.port }} stage
          echo "::endgroup::"
          echo "::group::Make check-plist"
          make -C ${{ matrix.port }} check-plist
          echo "::endgroup::"
          echo "::group::Make stage-qa"
          make -C ${{ matrix.port }} stage-qa
          echo "::endgroup::"
